language: minimal
addons:
  # add our deploy server to known hosts
  # you can set environmental variable in Travis GUI
  ssh_known_hosts: moon.scs.ryerson.ca

deploy:
  provider: script
  skip_cleanup: true
  script: scp -pw JklFds123! StartupToolsHelloWorld.html j83zhang@moon.scs.ryerson.ca:/home/j83zhang/cps847/Assignment2

# dd:
#- openssl aes-256-cbc -K $encrypted_272301d823e6_key -iv $encrypted_272301d823e6_iv
#  -in deploy_rsa.enc -out deploy_rsa -d
