language: minimal
addons:
  # add our deploy server to known hosts
  # you can set environmental variable in Travis GUI
  ssh_known_hosts: moon.scs.ryerson.ca

before_deploy:
  - openssl aes-256-cbc -K $encrypted_272301d823e6_key -iv $encrypted_272301d823e6_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: scp StartupToolsHelloWorld.html j83zhang@moon.scs.ryerson.ca:/home/avm/courses/cps847/j83zhang
  
# dd:
#- openssl aes-256-cbc -K $encrypted_272301d823e6_key -iv $encrypted_272301d823e6_iv
#  -in deploy_rsa.enc -out deploy_rsa -d
